# There is an issue with the following rule https://github.com/realm/SwiftLint/issues/2708
#identifier_name:
#  validates_start_with_lowercase: false # Also makes no sense and for enum values.

excluded: # paths to ignore during linting. Takes precedence over `included`.
  - Pods

reporter: "xcode" # reporter type
