name: Build & Tests

on: 
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]
  schedule:
    - cron: '30 5 * * 5'
    
jobs:

  build: 
    runs-on: macos-latest
    steps:
    - name: Checkout the code
      uses: actions/checkout@v2
    - name: Show xcodebuild version
      run: xcodebuild -version
    - name: Show xcode embedded SDKs
      run: xcodebuild -showsdks
    - name: Show buildable schemes
      run: xcodebuild -list -project ./DarkModeDiscovery/DarkModeDiscovery.xcodeproj
    - uses: mxcl/xcodebuild@v1.9.2 
      with:
        platform: macOS
        scheme: 'DarkModeDiscovery'
        action: build
        working-directory: ./DarkModeDiscovery
        verbosity: xcpretty
        upload-logs: always
        configuration: Release
        
  tests: 
    runs-on: macos-latest
    steps:
    - name: Checkout the code
      uses: actions/checkout@v2
    - name: Show xcodebuild version
      run: xcodebuild -version
    - name: Show xcode embedded SDKs
      run: xcodebuild -showsdks
    - name: Show buildable schemes
      run: xcodebuild -list -project ./DarkModeDiscovery/DarkModeDiscovery.xcodeproj
    - uses: mxcl/xcodebuild@v1.9.2 
      with:
        platform: macOS
        scheme: 'DarkModeDiscovery'
        action: test
        code-coverage: true
        working-directory: ./DarkModeDiscovery
        verbosity: xcpretty
        upload-logs: always
        configuration: Release
